# Generated by Django 2.0.4 on 2018-07-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=45)),
                ('comuna', models.CharField(max_length=45, null=True)),
                ('imagen', models.ImageField(upload_to='imagen_perfil')),
            ],
        ),
    ]
